# Generated by Django 2.2.6 on 2019-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='coments',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
